### PR TITLE
BO-69 Use Prismic.io CMS

### PR DESCRIPTION
**Pull request by vogdb**
Not ready yet. Just to keep track

### CODE REVIEW

**Comment by vogdb** [comment]
@njam It's ready but I have a question. Should I somehow order members? Currently they are randomly ordered cause Prismic does not have any order.

**Comment by njam** [comment]
Let's order by name.
I will review it shortly.

**Comment by vogdb** [comment]
one moment, I need to decide what to do with this special business card of `site.data.jobs.size > 0`

**Comment by vogdb** [comment]
@njam please review

**Comment by vogdb** [comment]
Shall I delete `_data/members.yml` file btw?

**Comment by njam** [comment]
yes, yes, yes!

**Comment by vogdb** [comment]
@njam please review

**Comment by njam** [comment]
@zazabe could you review this?

**Comment by christopheschwyzer** [comment]
I looked a bit into prismic. The docs are a bit incomprehensible :/ But I think for this issue it would make sense to use _slices_ (See example here https://prismic.io/docs/fields/slices) This way you could bundle all of the "team" content into one editable field. -> Cleaner, more manageable, ability to re-order elements, and you wouldn't have to use a "consultant" tag.

**Comment by christopheschwyzer** [comment]
Actually, I rather meant  _groups_. 

```json
{
  "Staff": {
    "image-staff": {
      "type": "Group",
      "fieldset": "Staff Member",
      "config": {
        "fields": {
          "illustration": {
            "type": "Image"
          },
          "caption": {
            "type": "Text",
            "config": {
              "placeholder": "Image caption..."
            }
          }
        }
      }
    }
  },
  "Consultants": {
    "image-consultants": {
      "type": "Group",
      "fieldset": "Staff Member",
      "config": {
        "fields": {
          "illustration": {
            "type": "Image"
          },
          "caption": {
            "type": "Text",
            "config": {
              "placeholder": "Image caption..."
            }
          }
        }
      }
    }
  }
}
```

**Comment by vogdb** [comment]
@zazabe please hold with the review then. I will use Christophe's hint with groups.

**Comment by vogdb** [comment]
@christopheschwyzer I agree that Groups seem to fit better but do you suggest to duplicate structure of Member in two Groups for Staff and Consultants? Shall we rather use one group and have an optional field `consultant` of Number type and values `[0, 1]` to mark group item as consultant?

**Comment by christopheschwyzer** [comment]
sgtm

**Comment by christopheschwyzer** [comment]
_Numbers_ is very technical. I would us a _select_ field with options "Staff" and "Consultants".

**Comment by njam** [comment]
There's also the concept of "collections" to represent groups of items of a specific "type". But I don't know how it is represented in the web UI. Did you see it anywhere? (could be that this is a deprecated feature even?)

**Comment by vogdb** [comment]
> _Numbers_ is very technical. I would us a _select_ field with options "Staff" and "Consultants". 

agree, done

**Comment by vogdb** [comment]
@zazabe please review

**Comment by vogdb** [comment]
> Did you see it anywhere?

Nope

**Comment by christopheschwyzer** [comment]
I noticed a few things to improve. Will take over.

**Comment by christopheschwyzer** [comment]
@njam 
- we currently don't have a preview functionality. You want to add it? Not sure it's necessary right now. 
- we don't use prismic for job announcements yet. I guess we can use it as soon as we need it.

**Comment by njam** [comment]
Agree, both are not needed for the moment

**Comment by christopheschwyzer** [comment]
@zazabe please review

**Comment by christopheschwyzer** [comment]
closes #164

**Pull request merged**
