### PR TITLE
Add SEO job to cargomedia.ch

### PR DESCRIPTION
**Pull request by christopheschwyzer**
**Senior Search Enginge Optimization Manager (m/f)**
The SEO Specialist will have a senior role and be responsible for improving the companies organic search results, audit, create and launch SEO campaigns (on-page and off-page) for our products and identify areas of improvement, run weekly reports to track project progress, rankings and sales.

*Responsibilities*
- Develop and implement effective SEO strategies that drive traffic and bolster conversion
- Oversee and organize original, powerful SEO content production for blogs and websites 
- Perform website audit and provide on-page and technical feedback
- Compile and present SEO performance and strategy reports showing weekly rankings and sales data
- Consult with web designers and developers to improve the navigation of a site to enhance its search engine ranking

*Requirements*
- Good command of English and intermediate knowledge of German
- Extensive experience with online marketing, including SEO and ability to improve ROI
- Strong background and understanding of web analytics
- Extensive experience in developing, maintaining and delivering on marketing strategies to meet company objectives

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
There is a typo in "Enginge" - can you change it to "Engine"? :D

@fabianfrey wanna double check the diff? Click on "Files changed" tab above.

**Comment by fabianfrey** [comment]
Hm, it already seems to have been corrected?

**Comment by njam** [comment]
Ok so I guess it's ready to go. Merging

**Pull request merged**
