### PR TITLE
Use docker to build the static website

### PR DESCRIPTION
**Pull request by zazabe**
Useful to avoid installing a full env on the host

### CODE REVIEW

**Comment by zazabe** [comment]
@christopheschwyzer please hold, #165 needs to be merged first :)

**Comment by christopheschwyzer** [comment]
@zazabe how can I test this?

**Comment by zazabe** [comment]
- install [docker for mac](https://docs.docker.com/docker-for-mac/install/)
- run `docker-compose up` in this repo

you should have the website running on `http://localhost:4000` normally :)

**Comment by zazabe** [comment]
finally i think we must keep npm packages out of the image, cause they need to be installed locally for grunt support.

@christopheschwyzer please review

**Pull request merged**
