### PR TITLE
Blogpost about mochajs forking.

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@kris-lab please review.

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Looks good. Is this up to date? You said you encountered some problems with forked tests is this code affected?

**Comment by vogdb** [comment]
@tomaszdurka please review.

**Comment by tomaszdurka** [comment]
Looks ok

**Pull request merged**
