### PR TITLE
Replace logo with SVG version

### PR DESCRIPTION
**Pull request by christopheschwyzer**

### CODE REVIEW

**Comment by christopheschwyzer** [comment]
I hope Google picks up the title tag.
@njam please review

**Comment by njam** [comment]
Should the logo be left-aligned with the sheet?

screen shot 2015-03-04 at 17 52 03

**Comment by christopheschwyzer** [comment]
Hm yes should be aligned with the text I guess. Will look into it. 
screen shot 2015-03-05 at 18 50 15

**Comment by christopheschwyzer** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Pull request merged**
