### PR TITLE
Added benchmark wowza on AWS blogpost

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- Add cross post note?
- Link to previous blogpost needs to be inserted

**Comment by kris-lab** [comment]
@njam what about now?

**Comment by njam** [comment]
Use relative link to blog post? Then it works independently of protocol schema and host (for example also in development).

**Comment by kris-lab** [comment]
@njam makes sense. please re-review

**Comment by njam** [comment]
lgtm

**Pull request merged**
