### PR TITLE
Add phpspec post

### PR DESCRIPTION
**Pull request by dlondero**

### CODE REVIEW

**Comment by dlondero** [comment]
@njam please review

**Comment by dlondero** [comment]
If needed code is in https://github.com/dlondero/phpspec-research and we could add it to the post.

**Comment by njam** [comment]
Great post, thanks!
Prophecy is indeed interesting! cc @tomaszdurka 

- Title: Should there be a separator? Like `phpspec: drive emergent design by specification`?
- Title: Should be title-cased - `phpspec - Drive Emergent Design by Specification`

**Comment by njam** [comment]
Not sure about a link to the full repo, you decide.

**Comment by dlondero** [comment]
@njam please review. Link not needed.

**Comment by njam** [comment]
looks good!

**Pull request merged**
